# Numpy


Using numpy we can perform <br>
Math and logical ops on arrays<br>
FOurier transform<br>
Linear algebra


how to import library?

In [37]:
import numpy as np

Create Array

In [39]:
a = np.array([1,2,3,4])

In [40]:
type(a)

numpy.ndarray

array coercion sequence

In [41]:
a = np.array([1,2,3,'four', 5])

In [42]:
a

array(['1', '2', '3', 'four', '5'], dtype='<U11')

In [44]:
np.array([1,2,3,1+20j, 5])

array([1. +0.j, 2. +0.j, 3. +0.j, 1.+20.j, 5. +0.j])

In [45]:
np.array([1,2,3,4.5, 5])

array([1. , 2. , 3. , 4.5, 5. ])

In [46]:
np.array([1,2,3,4, 5])

array([1, 2, 3, 4, 5])

arrays using linspace<br>

In [50]:
np.linspace(start=1, stop=100, num=100,endpoint=False, retstep=True)

(array([ 1.  ,  1.99,  2.98,  3.97,  4.96,  5.95,  6.94,  7.93,  8.92,
         9.91, 10.9 , 11.89, 12.88, 13.87, 14.86, 15.85, 16.84, 17.83,
        18.82, 19.81, 20.8 , 21.79, 22.78, 23.77, 24.76, 25.75, 26.74,
        27.73, 28.72, 29.71, 30.7 , 31.69, 32.68, 33.67, 34.66, 35.65,
        36.64, 37.63, 38.62, 39.61, 40.6 , 41.59, 42.58, 43.57, 44.56,
        45.55, 46.54, 47.53, 48.52, 49.51, 50.5 , 51.49, 52.48, 53.47,
        54.46, 55.45, 56.44, 57.43, 58.42, 59.41, 60.4 , 61.39, 62.38,
        63.37, 64.36, 65.35, 66.34, 67.33, 68.32, 69.31, 70.3 , 71.29,
        72.28, 73.27, 74.26, 75.25, 76.24, 77.23, 78.22, 79.21, 80.2 ,
        81.19, 82.18, 83.17, 84.16, 85.15, 86.14, 87.13, 88.12, 89.11,
        90.1 , 91.09, 92.08, 93.07, 94.06, 95.05, 96.04, 97.03, 98.02,
        99.01]), 0.99)

numpy arange

In [53]:
d = np.arange(5,51,5)
d

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

reshaping an array using reshape

In [62]:
d.reshape((5,2))

array([[ 5, 10],
       [15, 20],
       [25, 30],
       [35, 40],
       [45, 50]])

numpy ones array

In [67]:
o = np.ones((5,5))
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

numpy zeros array

In [70]:
z = np.zeros((5,5), dtype = int)
z


array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

numpy random array

In [72]:
r = np.random.rand(100)
r

array([0.14897188, 0.56386624, 0.33345559, 0.62281972, 0.20001688,
       0.19564389, 0.58062989, 0.93393172, 0.9771579 , 0.4720882 ,
       0.78477052, 0.12722785, 0.20897643, 0.03438374, 0.6152316 ,
       0.57591979, 0.96281796, 0.99112519, 0.00824472, 0.52264376,
       0.86982571, 0.1115931 , 0.97674306, 0.64915815, 0.6529795 ,
       0.7552348 , 0.30448038, 0.25589186, 0.20862365, 0.72686101,
       0.08325368, 0.02405687, 0.70997636, 0.82522617, 0.70573176,
       0.41222927, 0.82806736, 0.98462009, 0.14471832, 0.75348742,
       0.836003  , 0.5008544 , 0.51243469, 0.65914769, 0.7346839 ,
       0.14923547, 0.56569135, 0.25841984, 0.63926825, 0.68900482,
       0.65572303, 0.43255854, 0.30707262, 0.85460751, 0.14450511,
       0.20569988, 0.1880609 , 0.62273801, 0.85288758, 0.32090957,
       0.27202386, 0.4706667 , 0.13377366, 0.15526826, 0.62045014,
       0.66642872, 0.26128308, 0.07651837, 0.78542215, 0.69122825,
       0.89136439, 0.9163004 , 0.22587602, 0.56626163, 0.07777

In [74]:
r = np.random.randn(100)
r

array([ 0.52235276,  0.16559923, -0.53133104, -0.19331813, -0.07005826,
       -1.99435404, -0.19252373, -0.94391742,  0.77658137,  0.48448939,
        0.73737517,  0.20073192,  0.85831001,  1.75828278, -0.0270587 ,
        0.77284751,  0.35983842, -0.3169951 , -0.91325112,  0.31026065,
       -0.14297274, -1.23805476,  1.10248596, -1.15096939,  0.61197292,
        2.33053006,  0.42420732,  0.28937459,  0.57227443,  0.32881615,
        0.45272791, -0.08893759,  0.05121085,  0.46274914, -1.29615693,
       -1.57095927,  0.08498684, -0.24203309,  1.19006771,  1.46573804,
       -1.26240149, -0.63562819, -0.10766691,  1.10931301,  0.71155827,
       -0.26057503, -1.9149552 , -0.50936758,  0.6227861 , -0.27504597,
       -0.64349164, -1.09013413,  0.11627578, -1.11784113, -1.69487882,
        0.01022557,  1.21210874, -0.48991753,  0.26520111,  2.57401421,
       -0.67210178, -0.09155915, -0.27708446, -0.54631756,  0.97467751,
       -0.47910931, -1.34216905,  0.55862861,  0.12850283,  2.49

numpy logspace array

In [76]:
l = np.logspace(1, 10)
l

array([1.00000000e+01, 1.52641797e+01, 2.32995181e+01, 3.55648031e+01,
       5.42867544e+01, 8.28642773e+01, 1.26485522e+02, 1.93069773e+02,
       2.94705170e+02, 4.49843267e+02, 6.86648845e+02, 1.04811313e+03,
       1.59985872e+03, 2.44205309e+03, 3.72759372e+03, 5.68986603e+03,
       8.68511374e+03, 1.32571137e+04, 2.02358965e+04, 3.08884360e+04,
       4.71486636e+04, 7.19685673e+04, 1.09854114e+05, 1.67683294e+05,
       2.55954792e+05, 3.90693994e+05, 5.96362332e+05, 9.10298178e+05,
       1.38949549e+06, 2.12095089e+06, 3.23745754e+06, 4.94171336e+06,
       7.54312006e+06, 1.15139540e+07, 1.75751062e+07, 2.68269580e+07,
       4.09491506e+07, 6.25055193e+07, 9.54095476e+07, 1.45634848e+08,
       2.22299648e+08, 3.39322177e+08, 5.17947468e+08, 7.90604321e+08,
       1.20679264e+09, 1.84206997e+09, 2.81176870e+09, 4.29193426e+09,
       6.55128557e+09, 1.00000000e+10])

array dimensions using shape

In [81]:
o.shape


(5, 5)

<h3>Few Arithmatic operation</h3>
numpy.add()<br>
numpy.subtract()<br>
numpy.multiply()<br>
numpy.divide()<br>
numpy.remainder()<br>


In [90]:
A = np.array(([1,2,3,4],[4,5,6,7]))
B = np.array(([10,20,30,40],[4,3,2,1]))


In [91]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [92]:
B

array([[10, 20, 30, 40],
       [ 4,  3,  2,  1]])

In [93]:
np.add(A, B)

array([[11, 22, 33, 44],
       [ 8,  8,  8,  8]])

In [96]:
np.subtract(A, B)

array([[ -9, -18, -27, -36],
       [  0,   2,   4,   6]])

In [97]:
np.divide(A, B)

array([[0.1       , 0.1       , 0.1       , 0.1       ],
       [1.        , 1.66666667, 3.        , 7.        ]])

In [98]:
np.multiply(A, B)

array([[ 10,  40,  90, 160],
       [ 16,  15,  12,   7]])

Accessing components of an array

In [99]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [100]:
A[1,1]

5

In [105]:
A[0,2:]

array([3, 4])

Accessing component by index position

Extract selective elements row-wise and column-wise (subset)

update the values in subsetted array

In [106]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [108]:
A[1,3] = 77

In [109]:
A

array([[ 1,  2,  3,  4],
       [ 4,  5,  6, 77]])

In [110]:
A

array([[ 1,  2,  3,  4],
       [ 4,  5,  6, 77]])

In [113]:
subset = A[:,2:]
subset

array([[ 3,  4],
       [ 6, 77]])

In [115]:
subset[1,1] = 7

In [116]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

Note: Modifying the subset will also modify the original array as well

Modifying array using transpose()

In [117]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [118]:
A.transpose()

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

Modifying array using append()

In [128]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [136]:
new_row = np.array(([8,9,10,11], [12,13,14,15]))
new_row
new_row.shape

(2, 4)

In [142]:
C = np.append(A, new_row, axis=0)
A.shape

(2, 4)

In [143]:
C

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Modifying array using insert()

In [144]:
C

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Modifying array using delete()

In [148]:
np.insert(C,1,values=[9,9,9,9],axis=1)

array([[ 1,  9,  2,  3,  4],
       [ 4,  9,  5,  6,  7],
       [ 8,  9,  9, 10, 11],
       [12,  9, 13, 14, 15]])

# Metrices
Create Matrices<br>
Dimensions<br>
Modifying Matrices<br>
Accessing elements in matrix<br>
Matrix operations<br>
<img src = "Matris.png" width="300" height="300"> </img>



 <strong> Create a matrix

In [150]:
m= np.matrix('1,2,3;4,5,6;7,8,9')

In [151]:
type(m)

numpy.matrix

In [153]:
D = np.array(np.arange(25)).reshape(5,5)

In [155]:
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [156]:
np.matrix(D)

matrix([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]])

Matrix Properties
<br> shape()
<br> columns-rows

In [158]:
D.shape

(5, 5)

In [161]:
D.shape[1]

5

In [152]:
m.shape

(3, 3)

size()

In [163]:
np.size(D)

25

dot() and transpose()

In [164]:
A

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [170]:
B = np.transpose(B)
B

array([[10,  4],
       [20,  3],
       [30,  2],
       [40,  1]])

In [171]:
np.dot(A,B)

array([[300,  20],
       [600,  50]])

# Linear Algebra
Determinant<br>
Rank of matrix<br>
Inverse<br>
SOlve system of equation<br>

In [172]:
D

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [174]:
np.linalg.det(D)

0.0

<strong> Determinant: Only perform on sqaure matrix<br></strong>
    Syntaxt:numpy.linalg.det(matrix)
    

In [179]:
#np.linalg.det(A)

Rank of matrix: Linearly independent rows or cols

In [ ]:
#numpy.liaalg.matrix_rank(matrix)

In [181]:
C
np.linalg.matrix_rank(C)

2

In [182]:
C

array([[ 1,  2,  3,  4],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

Inverse of a matrix:<br>
numpy.linalg.inv(mat)

In [183]:
np.linalg.inv(C)

array([[ 7.98785374e+14, -6.11011200e+13, -2.07445754e+15,
         1.33677328e+15],
       [-2.28905659e+15,  1.78832546e+15,  2.71825471e+15,
        -2.21752358e+15],
       [ 2.18175707e+15, -3.39334757e+15,  7.86863204e+14,
         4.24727298e+14],
       [-6.91485846e+14,  1.66612322e+15, -1.43066037e+15,
         4.56022993e+14]])

np.matrix('2,1,2;1,0,1;3,1,3')

Linear Eq: Ax = B <br>
mat b must b transpose<br>
numpy.linalg.solve()

<img src = 'linear.png'>

In [187]:
A = np.matrix('3,1,2;3,2,5;6,7,8')
#x = np.matrix('x, y, z')
B = np.matrix('2,-1,3')
B = np.transpose(B)

np.linalg.solve(A,B)

matrix([[ 1.24242424],
        [ 0.81818182],
        [-1.27272727]])